### ISSUE TITLE
Prompt dismisses when running workflow for first time

### ISSUE THREAD

**Issue by nikivdev** [deanishe/alfred-gcal#1]
Most probably related to [this](https://github.com/deanishe/alfred-safari-assistant/issues/1) as it is the same issue I have there.

Here is the log I get when trying to run it: 

```Bash
[2017-11-30 15:29:47][input.keyword] Processing output of 'utility.argument' with arg ''
[2017-11-30 15:29:47][utility.argument] Processing output of 'output.callexternaltrigger' with arg ''
[2017-11-30 15:29:47][trigger.external] Processing output of 'utility.debug' with arg ''
[2017-11-30 15:29:47][utility.debug] .
/---- ACTION IN ----\
query=
variables={
    "APPLE_MAPS" = 1;
    "CALENDAR_APP" = "";
    "EVENT_CACHE_MINS" = 15;
    "SCHEDULE_DAYS" = 5;
    action = date;
}
\-------------------/
[2017-11-30 15:29:47][utility.debug] Processing output of 'utility.filter' with arg ''
[2017-11-30 15:29:47][utility.debug] Processing output of 'utility.filter' with arg ''
[2017-11-30 15:29:47][utility.debug] Processing output of 'utility.filter' with arg ''
[2017-11-30 15:29:47][utility.debug] Processing output of 'utility.filter' with arg ''
[2017-11-30 15:29:47][utility.debug] Processing output of 'utility.filter' with arg ''
[2017-11-30 15:29:47][utility.filter] Processing output of 'utility.argument' with arg ''
[2017-11-30 15:29:47][utility.argument] Processing output of 'input.scriptfilter' with arg ''
[2017-11-30 15:29:47][input.scriptfilter] Queuing argument ''
```

Thank you for any help.

**Comment by deanishe** [comment]
It sounds like the same problem, yes. There is nothing along that path that would close Alfred.

Unless someone else reports having the same issue, I'm going to assume that it's your system.

Have you tried turning off Karabiner—or whatever it is you're using that messes with keypresses—and running the workflow normally?

**Comment by nikivdev** [comment]
Just tried turning off Karabiner and running the workflow. I still get the same issue. 😞

That's a shame, it does seem like a really nice workflow.

**Comment by nikivdev** [comment]
Although it is most certainly something that has to do with my system.

In Safari Assistant, 0.4.3 release and below work for me but the new 0.4.4 breaks for me but looking at the commit, you haven't really changed much that would cause this I think. Perhaps this workflow also has something that doesn't play nice with my system. I am using El Captain.

**Comment by deanishe** [comment]
> 0.4.3 release and below work for me

Are you sure? Did you try re-installing 0.4.3 since you've been having the problem?

**Comment by nikivdev** [comment]
Yes. Just [tried it again](https://youtu.be/648fRfK_5Eg) and it works 100 % of times on old release.

**Comment by deanishe** [comment]
Could you try [v0.4.6](https://github.com/deanishe/alfred-safari-assistant/releases/tag/v0.4.6)?

**Comment by nikivdev** [comment]
That fixed it. 🎊 

I am curious, what was wrong? Can you also fix gcal workflow with it? 🙂

**Comment by deanishe** [comment]
> I am curious, what was wrong?

On the connections of the Script Filter that doesn't work for you, I'd forgotten to check the "Don't close Alfred Window on actioning result" option.

In theory, the only issue should be that flickering of Alfred's window that you hate, so there probably is actually something wrong with your setup (or the universe is just hating on you because it knows the flicker bothers you so much).

> Can you also fix gcal workflow with it?

Already done. Grab [v0.1.1](https://github.com/deanishe/alfred-gcal/releases/tag/v0.1.1).

**Comment by nikivdev** [comment]
Thank you @deanishe. Can confirm it works perfectly well. I don't actually use Google calendar but I appreciate the workflow and more importantly I have something more to read and study. 🙂 

> the only issue should be that flickering of Alfred's window that you hate

I actually changed my ways and 'wisened' up. I now really appreciate keywords, mostly due to [this](https://github.com/pochemuto/alfred-help-workflow) and I cannot wait until native solution for this arrives.

I still call my most used workflows from external triggers which more often than not include nearly all your workflows. I also stopped stripping Title and Placeholder with JSON utility because it is quite silly in hindsight.

I kind of wonder though how many workflows do you actually use? You've been using Alfred since version 1. I really want to make this [repo](https://github.com/learn-anything/alfred-workflows) include all the good stuff and wonder if there is things I am missing. Shame that Packal went down, it was a really awesome way to dive in and explore workflow creations. Nowadays you only have Alfred Forum and [GitHub recent](https://github.com/search?utf8=%E2%9C%93&amp;q=alfred&amp;type=Repositories&amp;ref=searchresults&amp;o=desc&amp;s=updated).

**Comment by deanishe** [comment]
> how many workflows do you actually use?

Depends how you count (I put most of my File Filters and File Actions in one workflow). Probably about 50–60, but only about 25 really regularly.
