### ISSUE TITLE
v0.2.0 not working

### ISSUE THREAD

**Issue by johnnypea** [deanishe/alfred-gcal#10]
The workflow doesn't work after upgrading to v0.2.0. Even when I fix the permissions for that file, events are not fetched from the calendars and I can't remove the accounts.

```
[2019-01-26 09:59:43][ERROR: input.scriptfilter] Code 126: /Users/johnnypea/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/82E438ED-C51C-402F-9D07-BDCDC1532615: line 1: ./gcal: Permission denied
```

**Comment by deanishe** [comment]
Sorry. It was a bad build.

Could you [download the workflow again and re-install](https://github.com/deanishe/alfred-gcal/releases/tag/v0.2.1)?

**Comment by johnnypea** [comment]
Thanks for fast response, but I still can't remove accounts and I can see no events.

**Comment by deanishe** [comment]
What does Alfred's debugger or the log file (`gcalconf workflow:log`) say?

**Comment by johnnypea** [comment]
No particular errors:

```
[2019-01-27 13:05:56][STDERR: input.scriptfilter] 🍺
13:05:56 workflow.go:304: ---- Google Calendar View/0.2.1 (AwGo/0.14.0) ----
13:05:56 config_bind.go:250: [bind] unbindable kind: struct
13:05:56 config_bind.go:250: [bind] unbindable kind: struct
13:05:56 main.go:176: [main] query="", startTime=2019-01-27 13:05:56.142632 +0100 CET, endTime=2019-01-28 13:05:56.142632 +0100 CET
13:05:56 account.go:80: [account] loaded "my-account@domain.tld"
13:05:56 account.go:80: [account] loaded "my-second-account@domain.tld"
13:05:56 update.go:159: Latest release: 0.2.0
13:05:56 feedback.go:453: Sent 10 result(s) to Alfred
13:05:56 workflow.go:382: ------------------- 7.655752ms -------------------
[2019-01-27 13:05:58][utility.debug] .
/---- ACTION IN ----\
query=my-account@domain.tld
variables={
    "APPLE_MAPS" = 0;
    "AW_SESSION_ID" = 43Y3RAXXXXYYYYENU1HXSFK4;
    "CALENDAR_APP" = "";
    "EVENT_CACHE_MINS" = 15;
    "SCHEDULE_DAYS" = 5;
    account = "my-account@domain.tld";
    action = logout;
}
\-------------------/
```

How could I completely reset the workflow? I can see the accounts even when I do no migrations and completely remove the workflow.

**Comment by deanishe** [comment]
`gcalconf workflow:reset` will delete all the workflow's data.

**Comment by deanishe** [comment]
I'd messed up the workflow's info.plist, which is why it wasn't working. [v0.2.2](https://github.com/deanishe/alfred-gcal/releases/tag/v0.2.2) should correctly delete the account without your needing to reset everything.

**Comment by johnnypea** [comment]
Working like a charm. Thank you.
