### ISSUE TITLE
Can't see events from two Google accounts at the same time

### ISSUE THREAD

**Issue by ralbertazzi** [deanishe/alfred-gcal#11]
Hi! First, this workflow is just awesome!

Unfortunately, I can't see events from two Google accounts at the same time.
This is what happens:
1. I log with Google account 1 and I choose my calendar. I can see events from Google account 1.
2. I also log with Google account 2 and I add a second calendar. Now I can see events from Google account 2 but not from Google account 1.
3. I remove Google account 2. Now I can see events from Google account 1 again.

I basically have a personal and a work Google account and if I could see them at the same time this workflow would definitely be perfect! Thanks a lot :)

**Comment by ralbertazzi** [comment]
Notice that I can see two calendars from the same Google account.

**Comment by deanishe** [comment]
I'm using the workflow with multiple accounts, too, and it's working just fine for me.

I'm afraid I can't say any more than that without more information. Please check the workflow's log file (enter `gdate workflow:log` in Alfred).

**Comment by ralbertazzi** [comment]
Ok I decribe you the new behavior.

1. I'm currently logged in with just 1 Google account (ACCOUNT1 containing CALENDAR1) and everything works fine
2. I log in with a second account (ACCOUNT2): can't see the events from this second account calendar CALENDAR2 (still seeing events from the first account).

I took a look at the logs and it seems that the CALENDAR2 gets associated with ACCOUNT1 and when it tries to retrieve the calendar it receives a 404 error from Google API. Here are the most significant logs (registering ACCOUNT2, associating the CALENDAR2 to ACCOUNT1, Google error):

```
17:35:16 ---- Google Calendar View/0.2.3 (AwGo/0.14.0) ----
17:35:16 Opening Google signin page;
17:35:16 Sent 1 result(s) to Alfred
17:35:16 [auth] starting local webserver on localhost:61432 ...
17:35:24 [preview] 10s since last request
17:35:34 [preview] 20s since last request
17:35:43 [auth] oauth2 state=<HIDDEN>
17:35:43 [auth] oauth2 code=<HIDDEN>
17:35:43 [auth] oauth2 error=
17:35:43 [auth] local webserver stopped
17:35:44 [preview] 30s since last request
17:35:44 [auth] fetching user info from https://openidconnect.googleapis.com/v1/userinfo ...
17:35:45 [auth] fetching user avatar ...
17:35:46 [icons] saved <HIDDEN>
17:35:46 [account] saved "ACCOUNT2"
17:35:47 [account] saved "ACCOUNT2"
17:35:47 ----------------- 30.612390351s ------------------


17:36:27 ---- Google Calendar View/0.2.3 (AwGo/0.14.0) ----
17:36:27 [bind] unbindable kind: struct
17:36:27 [bind] unbindable kind: struct
17:36:27 [main] query="", startTime=2019-03-07 00:00:00 +0100 CET, endTime=2019-03-08 00:00:00 +0100 CET
17:36:27 [account] loaded "ACCOUNT2"
17:36:27 [account] loaded "ACCOUNT1"
17:36:27 [update] fetching events for 2019-03-07 ...
17:36:27 [main] 9 calendar(s) in 2 account(s)
17:36:27 [update] 2 active calendar(s)
17:36:27 [account] account="ACCOUNT1", cal="CALENDAR1", start=2019-03-07 00:00:00 +0100 CET, end=2019-03-12 00:00:00 +0100 CET
17:36:27 [account] account="ACCOUNT1", cal="CALENDAR2", start=2019-03-07 00:00:00 +0100 CET, end=2019-03-12 00:00:00 +0100 CET

17:36:28 ---- Google Calendar View/0.2.3 (AwGo/0.14.0) ----
17:36:28 [bind] unbindable kind: struct
17:36:28 [bind] unbindable kind: struct
17:36:28 [main] query="", startTime=2019-03-07 00:00:00 +0100 CET, endTime=2019-03-08 00:00:00 +0100 CET
17:36:28 [account] loaded "ACCOUNT2"
17:36:28 [account] loaded "ACCOUNT1"
17:36:28 [main] 9 calendar(s) in 2 account(s)
17:36:28 2 active calendar(s)
17:36:28 progress: current=0, next=1
17:36:28 0 event(s) for 2019-03-07
17:36:28 Sent 4 result(s) to Alfred
17:36:28 ------------------- 3.211189ms -------------------
17:36:28 [update] ERR: fetching events for calendar "CALENDAR2": googleapi: Error 404: Not Found, notFound
17:36:28 [update] 5 event(s) in calendar "CALENDAR1"
<EVENTS from CALENDAR1 HIDDEN>
17:36:28 ------------------ 884.510834ms ------------------
```

**Comment by deanishe** [comment]
I've fixed the problem shown in the log file in [v0.2.4](https://github.com/deanishe/alfred-gcal/releases/tag/v0.2.4) (which you can also install via `gcalconf` in Alfred).

Hopefully, multiple accounts will now work correctly for you.

**Comment by ralbertazzi** [comment]
That was quick! Already downloaded and tested, it works :)

**Comment by deanishe** [comment]
Marvellous. Your log and analysis made it very easy to find the error.

Thanks for finding the bug.
