### ISSUE TITLE
No Accounts Configured

### ISSUE THREAD

**Issue by sakhnenko** [deanishe/alfred-gcal#112]
Can't get the workflow to configure. It takes me through the process of connecting my google account, and allowing all the permissions, all the way to the empty page with 'ok' status. But when I go to open Alfred and 'gcal' it, it once again tells me that I have "No Accounts Configured"

**Comment by limacohen** [comment]
I'm having the exact same issue. The strangest thing is, after going through the Google authorization thing there's no mention of this workflow in [Google's permissions page](https://myaccount.google.com/permissions) nor I receive any email from Google alerting me that an app has gained access to my account, which is usually how this goes.
