### ISSUE TITLE
gnew [<query>] not working

### ISSUE THREAD

**Issue by RoarG** [deanishe/alfred-gcal#17]
gnew keyword is not returning any results.

I don`t see the keyword in the setup in alfred either.

**Comment by deanishe** [comment]
The feature is in `master`. It hasn't been released yet.

**Comment by chrisyeung1121** [comment]
Great Work! I also noticed this issue and I am looking forward to this. :)

**Comment by deanishe** [comment]
The thing is, I don’t have the feature working *well* yet.

The adding works fine, but it requires existing users to sign out of Google and sign back in again to grant the workflow write permission, and the way that currently works kinda sucks…

**Comment by firesofmay** [comment]
Looking forward to this feature being added! Great workflow!

**Comment by danielpassos** [comment]
@deanishe Just a tip, if it's not released yet, remove it from the README. It makes people confused.
