### ISSUE TITLE
Can't bind account

### ISSUE THREAD

**Issue by nameryan** [deanishe/alfred-gcal#28]
Hi, 
after downloaded the latest version 0.2.4 and installed .
I typed the keyword "gcal" in alfred input box ,
then it noticed "No accounts configed."

I followed the guide , step by step.
first,  i choose the account (i have two account logined) , just like the pic1
<img width="726" alt="Xnip2019-08-14_10-26-43" src="https://user-images.githubusercontent.com/4004271/62990548-fe1d4a80-be7e-11e9-8e51-39f78b4f78fa.png">

second,  i allow the permission.
<img width="534" alt="Xnip2019-08-14_10-27-02" src="https://user-images.githubusercontent.com/4004271/62990559-07a6b280-be7f-11e9-9006-9cbbc337d6da.png">

after that ,the browser linked to a local address ,and display the  result "ok"
<img width="1211" alt="Xnip2019-08-14_10-24-10" src="https://user-images.githubusercontent.com/4004271/62990632-3de43200-be7f-11e9-89c4-0de916ca5a29.png">

but there's noting happened . 
**when i type "gcal ", it show "no accounts configed " again .**

ps: I have the two-step verification open with my google account.

here's the log. 

`Starting debug for 'Google Calendar View'

[2019-08-14 10:27:27][utility.debug] .
/---- ACTION IN ----\
query=
variables={
    "APPLE_MAPS" = 0;
    "CALENDAR_APP" = "";
    "EVENT_CACHE_MINS" = 15;
    "SCHEDULE_DAYS" = 5;
    action = date;
}
\-------------------/
[2019-08-14 10:27:27][STDERR: input.scriptfilter] 🍺
10:27:27 workflow.go:304: ---- Google Calendar View/0.2.4 (AwGo/0.14.0) ----
10:27:27 config_bind.go:250: [bind] unbindable kind: struct
10:27:27 config_bind.go:250: [bind] unbindable kind: struct
10:27:27 main.go:176: [main] query="", startTime=2019-08-14 10:27:27.375086 +0800 CST, endTime=2019-08-15 10:27:27.375086 +0800 CST
10:27:27 feedback.go:453: Sent 1 result(s) to Alfred
10:27:27 workflow.go:382: ------------------ 45.403414ms -------------------`

**Comment by deanishe** [comment]
> here's the log.

That doesn't show the authorisation process. Please check the log *file*, not the debugger. You can open it by entering `gdate workflow:log` in Alfred.

**Comment by nameryan** [comment]
it looks like not enough information.

<img width="970" alt="Xnip2019-08-16_13-30-06" src="https://user-images.githubusercontent.com/4004271/63145425-fe0d7e00-c029-11e9-8d57-c1158487b1ec.png">

**Comment by nameryan** [comment]
after i done the reset action.

<img width="671" alt="Xnip2019-08-16_13-34-19" src="https://user-images.githubusercontent.com/4004271/63145598-986dc180-c02a-11e9-8be9-cfe5a0bbd7b8.png">

find post google.com timeout , is it be related with the great firewall in China? i visit Google via proxy with Shadowsocks client on my MacOS.

**Comment by deanishe** [comment]
I don't know: I'm not familiar with the Great Firewall or Shadowsocks.

~The workflow doesn't support SOCKS proxies, only HTTP(S) proxies.~

~So if Shadowsocks works like a normal SOCKS proxy, the workflow will ignore it and try to connect directly.~

It looks like recent versions of Go *do* support SOCKS5 proxies. You could try adding an `HTTPS_PROXY` variable to the workflow's configuration sheet with a `socks5://` URL that points to your Shadowsocks client.

**Comment by nameryan** [comment]
thanks for your answer, i'v tried proxy but it don't work neither.

![image](https://user-images.githubusercontent.com/4004271/63325586-0aad1180-c35d-11e9-8ebb-5e18163d5e57.png)

and the same timeout error .

![image](https://user-images.githubusercontent.com/4004271/63325638-24e6ef80-c35d-11e9-99f6-256475e64b9b.png)

**Comment by deanishe** [comment]
Not in Alfred's preferences. In the workflow configuration sheet:

![image](https://user-images.githubusercontent.com/747913/63587838-433f2c00-c5a5-11e9-938e-b12657931d7d.png)

**Comment by nameryan** [comment]
It did't worked neither after i add HTTPS_PROXY or HTTP_PROXY to the workflow configuration.
IT still get stucked at the google net visiting (because of the GFW on China). 
the log is here.
![image](https://user-images.githubusercontent.com/4004271/63676291-3462ae80-c81d-11e9-9e9e-7a2b8c502e1f.png)


Then i used Proxifier which can set an app using socket5 proxy on MACOS.
and **IT WORKED.**.  OH YEE !
![image](https://user-images.githubusercontent.com/4004271/63676303-3cbae980-c81d-11e9-8e32-bf62ae554680.png)
Maybe the workflow proxy way doesn't work.

**Comment by deanishe** [comment]
> Maybe the workflow proxy way doesn't work.

It worked for me using ssh as a SOCKS5 proxy. But like I said, I don't know anything about Shadowsocks.
