### ISSUE TITLE
Quick Add feature?

### ISSUE THREAD

**Issue by deanishe** [deanishe/alfred-gcal#4]
Add an action to create a new calendar event via text entry.

https://www.alfredforum.com/topic/11016-google-calendar-view/?tab=comments#comment-58329

**Comment by sundarv85** [comment]
Hi, Love viewing the calendar.. any timeline when adding also will be available @deanishe .. if available, this could be a replacement for fantastical 2 for me.

**Comment by deanishe** [comment]
Not really, tbh. It's a fairly simple feature (it'll just send your query straight to the Google Calendar webpage). It's mostly a question of when I get around to working on this workflow again.

**Comment by deanishe** [comment]
The URL in the above-linked thread doesn't work, and I can't find one that does.

An "Add Event" action is still possible in the workflow, but only a dumb "click here to go to the 'Create Event' page" one.

Does anyone know a Google Calendar URL that accepts a natural-language query for a new event, e.g. "dentist's at 9 on friday"?

**Comment by MrBeardedGuy** [comment]
@deanishe just found this https://stackoverflow.com/questions/22757908/google-calendar-render-action-template-parameter-documentation

apparently it's something on these lines 

```https://www.google.com/calendar/render?
action=TEMPLATE&
text=EventName&
dates=20131206T050000Z/20131208T060000Z
&location=EventLocation&
sprop=name:Name&
sprop=website:EventWebite&
details=EventDetail&
sf=true&
output=xml```

**Comment by deanishe** [comment]
Thanks @MrBeardedGuy, but that URL's not suitable, as it requires the start/end dates to be specified.

I'm looking for either an endpoint that supports a natural-language query or no parameters at all. I don't want to add a full "add event" interface to the workflow. I think it would be clunky trying to enter all the details in Alfred. (It'll already be somewhat clunky if you have multiple accounts set up.)

I also don't want to try and implement a natural-language parser myself.

**Comment by MrBeardedGuy** [comment]
Ahh to bad this would have been a great feature even with the URL. 
Unfortunately Google Calendar removed the Natural language processing feature they had. https://www.howtogeek.com/338596/google-calendar-got-rid-of-its-best-feature-in-the-new-design/

**Comment by deanishe** [comment]
Oh, that sucks. Thanks for the info. The Calendar API doesn't have the feature, either.

I guess I can close this issue 🙁

**Comment by sundarv85** [comment]
Hi @deanishe Will integrating this parser help

https://github.com/olebedev/when

**Comment by deanishe** [comment]
Possibly. But the workflow was always intended to be essentially read only.

Adding an "Add Event" feature that just passes the input to a Google URL is a no-brainer: it's trivial to implement and any problems that arise are Google's fault, not mine.

I said earlier that I didn't want to try to implement natural-language parsing myself. It would be more accurate to say that I don't want to *support* (in the sense of "answer questions about and fix issues with") natural-language parsing.

It's not a feature I would personally use, and as such, I have little motivation to implement it and would have even less to maintain it.

If someone else submitted a PR for the feature **and assumed responsibility for maintaining it**, then sure.

But it's just not something I'm personally prepared to faff about with at this time.
