### ISSUE TITLE
Add Location

### ISSUE THREAD

**Issue by mattpanther** [deanishe/alfred-gcal#5]
Super useful workflow thanks for putting it together! One piece that's missing for me is to see location. For example on the attached image which shows after I've typed in gcal, adding location would give me a heading on where to go for my next meeting. I'm often needing to reference that when meetings are back-to-back. 
![gcal result](https://user-images.githubusercontent.com/22131722/40319140-13c19090-5cf5-11e8-969d-b3f306d3c345.png)

**Comment by deanishe** [comment]
Location is super important to me, too (I habitually go to the "regular" location, not the actual one).

Hit ⇧ or ⌘Y to view the Quicklook preview (which shows all event details).

Unfortunately, the Quicklook functionality is broken in several versions of macOS.
