### ISSUE TITLE
`The OAuth client was deleted.` -- is there a solution for this?

### ISSUE THREAD

**Issue by jayroh** [deanishe/alfred-gcal#53]
I looked everywhere and tried a bunch of things but either I'm totally missing something obvious or just don't know how to remediate this. 🤷‍♂ 

```
Error: deleted_client

The OAuth client was deleted.
```

![image](https://user-images.githubusercontent.com/28194/73869728-d816a880-4818-11ea-8b4d-2ed2f0bdb613.png)

Any ideas?

**Comment by deanishe** [comment]
Update the workflow. `gdate workflow:update`

**Comment by jayroh** [comment]
That got me a bit further, thank you! However:

```
Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.
```

Any pointers?

(If you'd prefer my starting up a new issue, I could do that instead of continuing this thread)
