### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by bhishanpdl** [deanishe/alfred-gcal#55]
Date: Feb 8, 2020
Browser: Chrome

I downloaded the Alfred workflow and tried to set up the workflow but I was greeted with following error messages:

Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

Is this workflow retired or if it working, how to circumvent the error?

Thanks for this awesome workflow, hope there are some workarounds.

**Comment by deanishe** [comment]
- #33 
- #48 
- #51
