### ISSUE TITLE
OSX not permitting to run

### ISSUE THREAD

**Issue by nrutman** [deanishe/alfred-gcal#56]
This looks like an awesome workflow. However, when I download it and install it, it appears that OSX is blocking it executing some script (see below).

![Screen Recording 2020-02-18 at 9 29 29 PM](https://user-images.githubusercontent.com/165184/74796351-530aa500-5296-11ea-9277-5b0ad9d44186.gif)

Is there anything I can do to get it to run properly? Thanks!

**Comment by deanishe** [comment]
https://github.com/deanishe/awgo/wiki/Catalina

**Comment by kenanmike** [comment]
I also had this issue and adding Alfred to developer tools also solved it for me. I think it's worth putting this in the readme/wiki.
