### ISSUE TITLE
3rd party calendars don't correct for timezone

### ISSUE THREAD

**Issue by mrrsm** [deanishe/alfred-gcal#8]
I have a calendar I am importing into google calendar that is using (GMT+00:00) Coordinated Universal Time for the timezone.  Google knows to correct for this when displaying on my calendar.

When it gets pulled into alfred it is still displaying in GMT as there is not a setting to correct for the timezone.

What I think I want to see is every calendar event date/time translated into the timezone I am currently in if possible.  If that is hard or less doable I would love to be able to set a default timezone to make sure things are displayed in.

**Comment by deanishe** [comment]
> the timezone I am currently in if possible

Should be easily fixed. I've checked, and it's just a display error.
