### ISSUE TITLE
Time for adding new events is wrong

### ISSUE THREAD

**Issue by zefaurios** [deanishe/alfred-gcal#88]
*Please refer to the answer below if you are facing problems with events being added at the wrong time, thank you.*

**Comment by deanishe** [comment]
`gnew` passes your input straight to the Google API, so this isn't really an issue with the workflow.

It sounds like it might be a timezone issue. Check your default timezone in Google Calendar settings.

**Comment by zefaurios** [comment]
> `gnew` passes your input straight to the Google API, so this isn't really an issue with the workflow.
> 
> It sounds like it might be a timezone issue. Check your default timezone in Google Calendar settings.

You are correct and thank you for this wonderful workflow.

I apologize for this embarrassing issue, as I checked all calendars but the default one for the correct timezone settings.

**Comment by deanishe** [comment]
No problem. I've changed the issue title back to the original one in case anybody else runs into the same issue.
