### ISSUE TITLE
No Accounts Configured!

### ISSUE THREAD

**Issue by zzzgithubzzz** [deanishe/alfred-gcal#93]
Hi,

Thank you for this workflow. I am trying to use your workflow. However, I keep getting the warning 'No Accounts Configured' even after repeatedly giving explicit access to my google account.

Am stuck now. How do I get around?

**Comment by deanishe** [comment]
Duplicate of #33 and #49.

Please search for your problem in existing issues before creating a new one.

**Comment by zzzgithubzzz** [comment]
Hi Dean,

Thank you for pointing me to the links that has the problem addressed.

The solutions worked for me as well after changing the default browser to safari.

Cheers!

Vinod
